version: "3.9"
name: Username Checker

services:
  # -------------------- BOT --------------------
  bot:
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    image: nezbut/username_checker:0.1.0
    environment:
      - USERNAME_CHECKER_BOT__FSM_STORAGE__NATS__CREATE_NATS_KV_BUCKETS=true
      - USERNAME_CHECKER_BOT__TOKEN__VALUE=${TGBOT_TOKEN:-None}
      - USERNAME_CHECKER_BOT__ADMIN__SUPERUSERS=[924589764]
      - USERNAME_CHECKER_DB__RDB__HOST=psql
      - USERNAME_CHECKER_DB__REDIS__HOST=redis
      - USERNAME_CHECKER_DB__RDB__USERNAME=superuser
      - USERNAME_CHECKER_DB__RDB__PASSWORD__VALUE=${DB_PASSWORD:-password}
      - USERNAME_CHECKER_DB__RDB__PORT=5432
      - USERNAME_CHECKER_BROKER__NATS__SERVERS=[{host='nats'}]
      - USERNAME_CHECKER_LOGGING__DEV=true
      - USERNAME_CHECKER_BOT__PROPERTIES__PARSE_MODE=html
    depends_on:
      - psql
      - redis
      - nats
      - tasks_worker

  tasks_worker:
    restart: unless-stopped
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    image: nezbut/username_checker:0.1.0
    environment:
      - USERNAME_CHECKER_BOT__FSM_STORAGE__NATS__CREATE_NATS_KV_BUCKETS=true
      - USERNAME_CHECKER_BOT__TOKEN__VALUE=${TGBOT_TOKEN:-None}
      - USERNAME_CHECKER_DB__RDB__HOST=psql
      - USERNAME_CHECKER_DB__REDIS__HOST=redis
      - USERNAME_CHECKER_DB__RDB__USERNAME=superuser
      - USERNAME_CHECKER_DB__RDB__PASSWORD__VALUE=${DB_PASSWORD:-password}
      - USERNAME_CHECKER_DB__RDB__PORT=5432
      - USERNAME_CHECKER_BROKER__NATS__SERVERS=[{host='nats'}]
      - USERNAME_CHECKER_LOGGING__DEV=true
      - USERNAME_CHECKER_BOT__PROPERTIES__PARSE_MODE=html
    entrypoint:
      [
        "taskiq",
        "worker",
        "username_checker.infrastructure.tkq.constants:taskiq_broker",
        "-tp",
        "**/tasks.py",
        "-fsd",
      ]
    deploy:
      replicas: 4
    depends_on:
      - nats
      - nats-nui
      - psql
      - redis

  migrate:
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    image: nezbut/username_checker:0.1.0
    profiles:
      - "migrate"
    restart: on-failure
    environment:
      - USERNAME_CHECKER_DB__RDB__HOST=psql
      - USERNAME_CHECKER_DB__RDB__USERNAME=superuser
      - USERNAME_CHECKER_DB__RDB__PASSWORD__VALUE=${DB_PASSWORD:-password}
      - USERNAME_CHECKER_DB__RDB__PORT=5432
    entrypoint: ["alembic", "-c", "config/alembic.ini", "upgrade", "head"]
    depends_on:
      - psql

  # -------------------- DATA BASES --------------------
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data:rw
    ports:
      - "6379:6379"

  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: username_checker
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d username_checker"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.12
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5252:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # -------------------- NATS --------------------
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
      - ../config/nats.conf:/config/server.conf
    command: -js -c /config/server.conf

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    ports:
      - "31311:31311"
    volumes:
      - nats-ui-data:/db
    depends_on:
      - nats

volumes:
  redis-data:
  psql-data:
  pgadmin-data:
  nats-ui-data:
  nats-data: